version: '3'

vars:
  TARGET_DIRS: ./garoh

tasks:
  default:
    deps: [all_for_ci, typo_check]

  all_for_ci:
    deps: [lint_node]

  lint_node:
    deps: [pnpm_test]


  yamllint:
    cmds:
      - >-
        find . \( -name node_modules -o -name .venv \) \
          -prune -o -type f -name '*.yml' -print \
        | xargs yamllint --no-warnings -c .yamllint.yml

  ruff:
    cmds:
      - ruff format --respect-gitignore --check
      - ruff check --respect-gitignore

  pnpm_test:
    cmds:
      - pnpm test

  shellcheck:
    cmds:
      - >-
        find {{ .TARGET_DIRS }} ./shellscripts -type f \
          | grep \.sh$ | xargs shellcheck

  typo_check:
    cmds:
      - typos -V && typos
