---
version: '3'

tasks:
  default:
    cmds:
      - task: format
      - task: lint_and_test

  lint_and_test:
    deps: [lint, test]

  format:
    cmds:
      - pnpm format

  lint:
    deps: [lint_pnpm]

  lint_pnpm:
    cmds:
      - pnpm lint

  lint_typos:
    cmds:
      - typos -V && typos

  test:
    cmds:
      - pnpm test
