---
version: '3'

tasks:
  default:
    deps: [format, lint, test]

  format:
    cmds:
      - pnpm format

  lint:
    cmds:
      - pnpm lint

  lint_shell:
    cmds:
      - >-
        find . \( -name node_modules -o -name .venv \) \
          -prune -o -type f -name '*.yml' -print \
        | xargs shellcheck

  lint_typos:
    cmds:
      - typos -V && typos

  test:
    cmds:
      - pnpm test
